# docker-compose.yml
version: '3.8'

services:
  app-demo4:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
        REPOSITORY: ${REPOSITORY}
    image: app-demo4
    container_name: app-demo4
    restart: unless-stopped
    ports:
      - "${PORT}:3000"
    networks:
      - webnet

networks:
  webnet:
    external: true
